# Generated by Django 5.1.3 on 2024-11-15 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_stanowisko_osoba'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='osoba',
            name='stanowisko',
        ),
        migrations.AlterField(
            model_name='osoba',
            name='plec',
            field=models.IntegerField(choices=[(1, 'Kobieta'), (2, 'Mezczyzna'), (3, 'Inne')], default=1),
        ),
        migrations.AlterField(
            model_name='stanowisko',
            name='nazwa',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='stanowisko',
            name='opis',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
