# Generated by Django 5.1.3 on 2024-11-15 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_osoba_stanowisko_alter_osoba_plec_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='osoba',
            name='stanowisko',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.stanowisko'),
        ),
    ]
